[package]
name = "async_fn_boxed"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2.version = "1.0.85"
quote.version = "1.0.36"
syn.features = [
    "full",
    "visit-mut",
]
syn.version = "2.0.66"

[dev-dependencies]
trybuild = "1.0.96"
